name: Workflow with inputs
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to use
        required: true
        default: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying using branch ${{ github.event.inputs.branch }}"
